---
firefox_version: '46.0'
firefox_lang: 'en-US'

firefox_link_dir: '/usr/local/bin'
firefox_install_root: '/opt'

firefox_release_root_url: 'https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/'


firefox_fonts: [ 'xfonts-100dpi', 'xfonts-75dpi', 'xfonts-cyrillic', 'xorg', 'dbus-x11' ]