---

# 1) ORDER OF EXECUTION OF SUITES IS ALPHABETICALLY. CAN NOT CONFIGURED
# IF --suite PARAM IS NOT PASSED, HOOKS DO NOT WORK.

# 2) *** IMPORTANT *** : Do not extend contexts that provide step definitions

# 3) default => autoload
#    Do not use because suites are located in different folders and src path is set in composer.json
#    autoload: [ %paths.base%/../src ]


# DEFAULT PROFILE
default:

    formatters:
        pretty:
            verbose: true
            paths: false
            snippets: true

        # e.g. ./bin/behat --config app/config/behat.yml --suite=dummy --format=progress (just shows ....)
        progress: ~

    calls:
        error_reporting: 14335 # E_ALL & ~E_USER_DEPRECATED


    suites:

        # DEFAULT SUITE (The configuration is not inherited)
        default:
            mink_session: goutte
            mink_javascript_session: selenium2
            paths: [ '%paths.base%/../../src/AppBundle/Tests/MinkBehat' ]
            contexts:
                - Behat\MinkExtension\Context\MinkContext
                - AppBundle\Tests\MinkBehat\BaseStepsContext

        routing:
            mink_session: goutte
            # mink_javascript_session: selenium2
            paths: [ '%paths.base%/../../src/AppBundle/Tests/MinkBehat/Routing/Features' ]
            filters:
            contexts:
                - Behat\MinkExtension\Context\MinkContext
                - AppBundle\Tests\MinkBehat\BaseStepsContext
                - AppBundle\Tests\MinkBehat\Routing\Features\Context\FeatureContext


        contact_form:
            mink_session: symfony2 #  symfony2|goutte => symfony2 value allows Intercepting redirections
            mink_javascript_session: selenium2
            paths: [ '%paths.base%/../../src/AppBundle/Tests/MinkBehat/ContactForm/Features' ]
            # filters:
            contexts:
                - Behat\MinkExtension\Context\MinkContext
                - AppBundle\Tests\MinkBehat\BaseStepsContext
                - AppBundle\Tests\MinkBehat\ContactForm\Features\Context\FeatureContext


        # Multiple Custom FeatureContexts
        # Important: Do not extend contexts that provide step definitions
        hooks:
            mink_session: goutte
            # mink_javascript_session: selenium2
            paths: [ '%paths.base%/../../src/AppBundle/Tests/MinkBehat/Hooks/Features' ]
            filters:
            contexts:
                - Behat\MinkExtension\Context\MinkContext
                - AppBundle\Tests\MinkBehat\BaseStepsContext
                - AppBundle\Tests\MinkBehat\Hooks\Features\Context\HelloWorldFeatureContext:
                    searchInputTextId: "searchInput"
                    findButtonClassName: "pure-button-primary-progressive"
                - AppBundle\Tests\MinkBehat\Hooks\Features\Context\PurgueDatabaseFeatureContext
                - AppBundle\Tests\MinkBehat\Hooks\Features\Context\HooksFeatureContext



        subscription:
            mink_session: goutte
            mink_javascript_session: selenium2
            paths: [ '%paths.base%/../../src/AppBundle/Tests/MinkBehat/Subscription/Features' ]
            filters:
            contexts:
                - Behat\MinkExtension\Context\MinkContext
                - AppBundle\Tests\MinkBehat\BaseStepsContext
                - AppBundle\Tests\MinkBehat\Subscription\Features\Context\FeatureContext

        product:
            mink_session: goutte
            mink_javascript_session: selenium2
            paths: [ '%paths.base%/../../src/AppBundle/Tests/MinkBehat/Product/Features' ]
            filters:
            contexts:
                - Behat\MinkExtension\Context\MinkContext
                - AppBundle\Tests\MinkBehat\BaseStepsContext
                - AppBundle\Tests\MinkBehat\Product\Features\Context\FeatureContext

        login:
            mink_session: goutte
            mink_javascript_session: selenium2
            paths: [ '%paths.base%/../../src/AppBundle/Tests/MinkBehat/Login/Features' ]
            filters:
            contexts:
                - AppBundle\Tests\MinkBehat\Login\Features\Context\LoginFeatureContext
                - AppBundle\Tests\MinkBehat\Hooks\Features\Context\PurgueDatabaseFeatureContext

    extensions:

        Behat\Symfony2Extension:
            kernel:
                path: app/AppKernel.php # It's not a must
                class: AppKernel # It's not a must
                env: test
                debug: true

        Behat\MinkExtension:
            base_url: http://localhost:8000/app_test.php
            show_auto: false
            symfony2: ~
            default_session: goutte
            javascript_session: selenium2

            sessions:
                default:
                    symfony2: ~
                goutte:
                    goutte: ~
                selenium2:
                    selenium2:
                        wd_host: "http://127.0.0.1:4444/wd/hub"

            browser_name: firefox
            # browser_name: chrome

        Cjm\Behat\StepThroughExtension: ~ # Debugging by pausing on every step
        SensioLabs\Behat\PageObjectExtension: ~ # PageObject

# ANOTHER PROFILE (can override)
otherProfile:
    suites:
        default:
            param: otherValue

# To run a profile pass the -p parameter. Eg: "behat -p chrome"
chrome:
    extensions:
        Behat\MinkExtension:
            browser_name: chrome

firefox:
    extensions:
        Behat\MinkExtension:
            browser_name: firefox