services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
<<<<<<< HEAD
            - { name: twig.extension }

    # The project was originally created in Symfony 2.8 and autowire was not considered
    # Consider only in one case for demo purposes
    _defaults:
        autowire: false
        autoconfigure: false
    # loads services from whatever directories you want (you can add directories!)
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '%kernel.project_dir%/src/AppBundle/{Twig}'
=======
            - { name: twig.extension }
>>>>>>> f1e28cf3bf484eac08fc32c4bbd86d88bfdea34b
