---
- name: Create mailcatcher group
  group: name=mailcatcher
  sudo: yes

- name: Create Mailcatcher user
  user: name=mailcatcher shell=/bin/bash comment="Mailcatcher" group=mailcatcher
  sudo: yes
