---
- include: firefox_check.yml

- include: firefox_install_common.yml
  when: firefox_needs_install is defined

- include: firefox_install_linux.yml
  when: ((ansible_system == 'Linux') and
         (firefox_needs_install is defined))

- include: firefox_cleanup.yml

- include: firefox_fonts.yml