AppBundle\Entity\Product:
    product_1{1..101}:
        name: <firstName()>
        price: <numberBetween(5,300)>
        description: <sentence()>
        category: @category_*
        createdAt: '<dateTimeBetween("-30 days", "now")>'

    product_rocky_1:
        name: 'Rocky I'
        price: 24.99
        description: 'Rocky Balboa, a small-time boxer, gets a supremely rare chance to fight the heavy-weight champion, Apollo Creed, in a bout in which he strives to go the distance for his self-respect.'
        category: <category_name('Films')>
        createdAt: '<dateTimeBetween("-30 days", "now")>'

    product_rocky_2:
        name: 'Rocky II'
        price: 19.95
        description: 'Rocky struggles in family life after his bout with Apollo Creed, while the embarrassed champ insistently goads him to accept a challenge for a rematch.'
        category: @category_films
        createdAt: '<dateTimeBetween("-30 days", "now")>'

    product_rocky_5:
        name: 'Rocky V'
        price: 14.85
        description: "Reluctantly retired from boxing and back from riches to rags, Rocky takes on a new protege who betrays him; As the champ's son must adjust to his family's new life after bankruptcy."
        category: @category_films
        createdAt: '<dateTimeBetween("-30 days", "now")>'

    product_rambo:
        name: 'RAMBO'
        price: 14.85
        description: "Former Green Beret John Rambo is pursued into the mountains surrounding a small town by a tyrannical sheriff and his deputies, forcing him to survive using his combat skills."
        category: @category_films
        createdAt: '<dateTimeBetween("-30 days", "now")>'