---

- name: Update apt cache (Debian).
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure git is installed
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ git_packages }}"

