---
- name: stop mailcatcher
  service: name=mailcatcher state=stopped
  sudo: yes
  ignore_errors: True

- name: start mailcatcher
  service: name=mailcatcher state=started
  sudo: yes
  ignore_errors: True

- name: restart mailcatcher
  service: name=mailcatcher state=restarted
  sudo: yes
  ignore_errors: True
