---
apt_cache_valid_time: 86400

php_fpm_pools:
 - name: '{{ web_user }}'
   user: '{{ web_user }}'
   group: '{{ web_group }}'
#   listen: 9000
   listen: /var/run/php5-fpm.sock
   listen.owner: '{{ web_user }}'
   listen.group: '{{ web_group }}'
#   chdir: /

php_fpm_pool_defaults:
  pm: dynamic
  pm.max_children: 5
  pm.start_servers: 2
  pm.min_spare_servers: 1
  pm.max_spare_servers: 3
  pm.status_path: /status
  pm.max_requests: 50

php_fpm_apt_packages:
  - php5.6
  - php5-fpm
  - php5-curl
  - php5-mysql
  - php5-gd
  - php5-intl
  - php5-mcrypt
  - php5-redis
  - php5-geoip
  - php5-memcache

php_fpm_default_pool:
  delete: yes
  name: 'www.conf'

php_fpm_ini:
 - option: "engine"
   section: "PHP"
   value: "1"
 - option: "error_reporting"
   section: "PHP"
   value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
 - option: "ldap.max_links"
   section: "ldap"
   value: "1"

php_fpm_config:
 - option: "error_log"
   section: "global"
   value: "/var/log/php5-fpm.log"
